{
    "ISSEMYM": {
      "folios": {

"1.01":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "VE-1 TIPO HONGO, MCA. LOREN COOK, MOD. 195ACEB, CAP. 4800 CFM"
},
"1.02":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "VE-2 TIPO HONGO, MCA. LOREN COOK, MOD. 180ACEB, CAP. 2745 CFM"
},
"1.03":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "VE-3 TIPO HONGO, MCA. LOREN COOK, MOD. 150ACEB, CAP. 1680 CFM"
},
"1.04":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "VE-4 TIPO HONGO,  MCA. LOREN COOK, MOD. 100ACEB, CAP. 600 CFM"
},
"1.05":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "VE-5 TIPO HONGO,  MCA. LOREN COOK, MOD. 100ACEB, CAP. 600 CFM"
},
"1.06":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "VE-6 TIPO HONGO, MCA. LOREN COOK, MOD. 270ACEB, CAP. 7320 CFM"
},
"1.07":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "VE-7 TIPO HONGO, MCA. LOREN COOK, MOD. 150ACEB, CAP. 2240 CFM"
},
"1.08":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "VE-8 MCA. SOLER & PALAU,  MOD. TD, CAP. 100 CFM"
},
"1.09":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "VE-9 TIPO HONGO, MCA. LOREN COOK, MOD. 195ACEB, CAP. 5140 CFM"
},
"1.10":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "VE-10 TIPO HONGO, MCA. LOREN COOK, MOD. 70ACEB, CAP. 260 CFM"
},
"1.11":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "VE-11 TIPO HONGO, MCA. LOREN COOK, MOD. 150, CAP. 2340 CFM"
},
"1.12":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "VE-12 TIPO HONGO, MCA. LOREN COOK, MOD. 100ACEB, CAP. 890 CFM"
},
"1.13":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "VE-13 TIPO HONGO, MCA. LOREN COOK, MOD. 100ACEB, CAP. 765 CFM"
},
"1.14":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "VE-14,  TIPO HONGO, MCA SOLER & PALAU, MOD. CM-110, CAP. 34000 CFM"
},
"1.15":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "VE-15 TIPO VENT-SET, MCA LOREN COOK,  MOD 135CPS, CAP. 3800 CFM"
},
"1.16":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "VE-16 TIPO HONGO, MCA. LOREN COOK, MOD. 100ACEB, CAP. 1000 CFM"
},
"1.17":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "VE-17 TIPO HONGO, MCA. LOREN COOK, MOD. 195ACEB, CAP. 5790 CFM"
},
"1.18":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "VE-18 TIPO HONGO, MCA. LOREN COOK, MOD. 165ACEB, CAP 3120 CFM"
},
"1.19":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "VE-19 TIPO HONGO, MCA. LOREN COOK, MOD. 195ACE, CAP. 3805 CFM"
},
"1.20":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "VE-20 TIPO HONGO, MCA. LOREN COOK, MOD. 80ACEB, CAP. 520 CFM"
},
"1.21":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "VE-21 TIPO HONGO, MCA. LOREN COOK, MOD. 300ACEB, CAP. 10000 CFM"
},
"1.22":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "VE-22 TIPO HONGO, MCA. LOREN COOK, MOD. 180ACEB, CAP. 4915 CFM"
},
"1.23":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "VE-23 TIPO HONGO, MCA. LOREN COOK, MOD. 165ACEB, CAP. 3060 CFM"
},
"1.24":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "VE-27 TIPO HONGO, MCA. LOREN COOK, MOD. 100ACEB, CAP. 600 CFM"
},
"1.25":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "VE-28 TIPO HONGO, MCA. LOREN COOK, MOD. 100ACEB, CAP. 800 CFM"
},
"1.26":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "VE-29 TIPO HONGO, MCA. LOREN COOK, MOD. 100ACEB, CAP. 900 CFM"
},
"1.27":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "VE-30 TIPO HONGO, MCA. LOREN COOK, MOD. 70ACEB, CAP. 320 CFM"
},
"1.28":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "VE-31 TIPO HONGO, MCA. LOREN COOK, MOD. 100ACEB, CAP. 540 CFM"
},
"1.29":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "VE-32 TIPO HONGO, MCA. LOREN COOK, MOD. 100ACEB, CAP. 700 CFM"
},
"1.30":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "VE-33 TIPO HONGO,  MCA. LOREN COOK, MOD. 70ACEB, CAP. 200 CFM"
},
"1.31":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "VE-34 TIPO HONGO, MCA. LOREN COOK, MOD. 135ACEB, CAP. 1800 CFM"
},
"1.32":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "VE-35 TIPO HONGO, MCA. LOREN COOK, MOD. 135ACEB, CAP. 1800 CFM"
},
"1.33":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "VE-36 TIPO HONGO, MCA LOREN COOK, MOD. 80ACEB, CAP. 480 CFM"
},
"1.34":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "VE-37 TIPO VENT-SET, MCA. LOREN COOK,  MOD. 60CPS, CAP. 380 CFM"
},
"1.35":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "VE-38 TIPO HONGO, MCA. LOREN COOK, MOD. 100ACEB, CAP. 960 CFM"
},
"1.36":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "VE-39 TIPO HONGO, MCA. LOREN COOK, MOD. 100ACEB, CAP. 360 CFM"
},
"1.37":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "VE-40 TIPO HONGO, MCA. LOREN COOK, MOD. 150ACEB, CAP. 780 CFM"
},
"1.38":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "VE-41 TIPO HONGO, MCA. LOREN COOK, MOD. 135ACEB, CAP. 2340 CFM"
},
"1.39":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "VE-42 TIPO HONGO, MCA. LOREN COOK, MOD. 135ACEB, CAP. 1920 CFM"
},
"1.40":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "VE-43, MCA. SOLER & PALAU,  MOD TD, CAP. 370 CFM"
},
"1.41":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "VE-44 TIPO HONGO, MCA. LOREN COOK, MOD. 100ACEB, CAP. 960 CFM"
},
"1.42":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "VE-45 TIPO VENT-SET, MCA. LOREN COOK, MOD. 70CPS, CAP. 640 CFM"
},
"1.43":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "VE-46 TIPO VENT-SET,  MCA. LOREN COOK, MOD. 60CPS, CAP. 380 CFM"
},
"1.44":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "CHILLER MCA. MC QUAY, MOD. WSCO48-BAAA, SERIE STN00220200179 DE 100 T.R."
},
"1.45":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "CHILLER MCA. MC QUAY, MOD. WSCO48-BAAA, SERIE STN0020200186 DE 100 T.R."
},
"1.46":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "CHILLER MCA. MC QUAY, MOD. WSCO48-BAAA DE 100 T.R."
},
"1.47":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "UMA-1 MCA. MC QUAY, MOD. EAH021AD, No. SERIE OP0096-02, 10 HP."
},
"1.48":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "UMA-2 MCA. MC QUAY, MOD. EAH021AD, No. SERIE OP0093-03, 15 HP."
},
"1.49":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "UMA-3 MCA. MC QUAY, MOD.EAH017AD, No. SERIE OP0096-04, 15 HP."
},
"1.50":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "UMA-4 MCA. MC QUAY, MOD.EAH017AU, No. SERIE OP0096-05, 10  HP."
},
"1.51":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "UMA-5 MCA. MC QUAY, MOD. EAH08ADNo. SERIE OP0096-06, 5 HP."
},
"1.52":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "UMA-6 MCA. MC QUAY, MOD. EAH017AD, No. SERIE OP0096-04, 5 HP."
},
"1.53":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "UMA-7 MCA. MC QUAY, MOD. EAH017AD, No. SERIE OP0096-08, 7,5 HP."
},
"1.54":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "UMA-8 MCA. MC QUAY, MOD. EAH006AD, No. SERIE OP0096-09, 5 HP."
},
"1.55":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "UMA-9 MCA. MC QUAY, MOD. EAH006AD, No. SERIE OP0096-10, 5 HP."
},
"1.56":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "UMA-10 MCA. MC QUAY, MOD. EAH010AD, No. SERIE OP0096-11, 5 HP."
},
"1.57":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "UMA-11 MCA. MC QUAY, MOD. EAH0210AD, No. SERIE OP0096-12, 10 HP."
},
"1.58":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "UMA-12 MCA. MC QUAY, MOD. EAH0140AD, No. SERIE OP0096-13, 5 HP."
},
"1.59":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "UMA-13 MCA. MC QUAY, MOD. EAH014AD, No. SERIE OP0096-14, 15 HP."
},
"1.60":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "UMA-14 MCA. MC QUAY, MOD. EAH012AD, No. SERIE OP0096-15, 5HP."
},
"1.61":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "UMA-15 MCA. MC QUAY, MOD. EAH014AH, No. SERIE OP0096-16, 7,5 HP."
},
"1.62":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "UMA-16 MCA. MC QUAY, MOD. EAH012AD, No. SERIE OP-0096-17, 7 HP."
},
"1.63":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "UMA-17 MCA. MC QUAY, MOD. EAH014AD, No. SERIE OP-0096-18, 10 HP."
},
"1.64":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "UMA-18 MCA. MC QUAY, MOD. EAH0120AD, No. SERIE OP0096-19, 7.5 HP."
},
"1.65":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "UMA-19 MCA. MC QUAY, MOD. EAH0120AD, No. SERIE OP0096-21, 7,5 HP."
},
"1.66":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "UMA-20 MCA. MC QUAY, MOD. EAH012AD, No. SERIE OP0096-21, 7 HP."
},
"1.67":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "UMA-21 MCA. MC QUAY, MOD. EAH017AD No. SERIE OP0096-22, 7.5 HP."
},
"1.68":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "UMA-22 MCA. MC QUAY, MOD. EAH017AD, No. SERIE OP0096-22, 7.5 HP."
},
"1.69":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "UMA 25 MCA. MC QUAY, MOD. EAH10AV, No. SERIE 090096-23 MOTOR DE 7,5 H.P."
},
"1.70":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "V1-1, UNIZONA, MOD. CAH050, 36860 CFM, 15 HP,"
},
"1.71":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "V1-2, UNIZONA, MOD. CAH008, 5060 CFM, 3 HP,"
},
"1.72":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "V1-3, UNIZONA, MOD. CAH006, 4590 CFM, 2 HP,"
},
"1.73":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "MINISPLIT MCA. MCQUAY, MOD. MQS- 102424-CWF216A, No. SERIE F0203151665, CONDENSADOR MCA. BALDOR  DE 15 H.P. (FARMACIA 1)"
},
"1.74":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "MINISPLIT MCA. JOHNSON CONTROLS , MOD. YJDA18FS-ADA, No. SERIE 505402594100400000, CONDENSADOR MCA. BALDOR  DE 15 H.P. (TOMOGRAFÍA 2)"
},
"1.75":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "MINISPLIT MCA. YORK,  DE 15 HP MOD. H2CM012AG, No. SERIE RMF2197FP, CONDENSADOR MCA. YORK  DE 15 H.P. (IMAGENOLOGÍA 3)"
},
"1.76":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "MINISPLIT MCA. MC QUAY, MOD. HDC12-1AT, No. SERIE 103401778, CONDENSADOR MCA. MC QUAY DE 1/5 H.P. (IMAGENOLOGÍA 4)"
},
"1.77":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "MINISPLIT MCA. MC QUAY, MOD. HDC12-1AT, No. SERIE 103401779, CONDENSADOR MCA. MC QUAY  DE 1/5 H.P. (DIRECCIÓN 5)"
},
"1.78":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "MINISPLIT MCA. YORK, MOD. ACO24M1021CA, No. SERIE WFNM086894, CONDENSADOR MCA. YORK  DE 1 H.P. (TOMOGRAFÍA 6)"
},
"1.79":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "MINISPLIT MCA. YORK, MOD. MCH25P17, No. SERIE 01-0846896, CONDENSADOR MCA. YORK  DE 1/8 H.P. (RECURSOS FINANCIEROS 7)"
},
"1.80":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "MINISPLIT MCA. MC QUAY, MOD. HDP18-1A, No. SERIE 102509726, CONDENSADOR MCA. YORK  DE 1/15 H.P. (AUDITORIO 8)"
},
"1.81":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "TORRE DE ENFRIAMIENTO 1 MCA. BALTIMORE, MOD. FXT87, No. SERIE 2367702, TIPO FLUJO CRUZADO DE UNA CELDA P/MANEJAR UN GASTO DE 279 GMP CON TEMPERATURA DE ENTRADA Y SALIDA DE 85ºF Y 75º RESPECTIVAMENTE, EQUIPADO CON VENTILADORES AXIALES, ACOPLADO POR MEDIO DE POLEA Y BANDA A MOTOR ELÉCTRICO DE 5 HP."
},
"1.82":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "TORRE DE ENFRIAMIENTO 2 MCA. BALTIMORE, MOD. FXT87, No. SERIE 2367702, TIPO FLUJO CRUZADO DE UNA CELDA P/MANEJAR UN GASTO DE 279 GMP CON TEMPERATURA DE ENTRADA Y SALIDA DE 85ºF Y 75º RESPECTIVAMENTE, EQUIPADO CON VENTILADORES AXIALES, ACOPLADO POR MEDIO DE POLEA Y BANDA A MOTOR ELÉCTRICO DE 5 HP."
},
"1.83":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "H-1, MCA. ORIFICE, MOD. HEM 90, No. SERIE 313/34-40-2-2-2, 14.0 LB/HR"
},
"1.84":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "H-2, MCA. AMSTRONG, MOD. 313134-40-1-0-2, No. SERIE 02A05807, 27.8 LB/HR"
},
"1.85":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "H-3, MCA. AMSTRONG, MOD. 313134-50-3-02, No. SERIE 313134-50-3-02, 32.4 LB/HR"
},
"1.86":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "H-4, MCA. AMSTRONG, MOD. HEM90, No. SERIE 02C09569, 56.8 LB/HR"
},
"1.87":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "H-5, MCA. AMSTRONG, MOD. HEM90, No. SERIE 313131-30-1-02, 20.2 LB/HR"
},
"1.88":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "H-6, MCA. AMSTRONG, MOD. HEM90, No. SERIE 313134-20-1-02, 19.3 LB/HR"
},
"1.89":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "H-7, MCA. AMSTRONG, MOD. HEM90, No. SERIE 313134-30-1-2, 62.0 LB/HR"
},
"1.90":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "H-8, MCA. AMSTRONG, MOD. HEM91, No. SERIE 313134-70-2-20, 220.1 LB/HR"
},
"1.91":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "H-9, MCA. AMSTRONG, MOD. HEM91, No. SERIE 313134-70-2-20, 31.1 LB/HR"
},
"1.92":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "H-10, MCA. AMSTRONG, MOD. HEM91, No. SERIE 313131-70-2-20, 24.0 LB/HR"
},
"1.93":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "H-11, MCA. AMSTRONG, MOD. HEM91, No. 313134-70-03-02, 14.8 LB/HR"
},
"1.94":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "H-12, MCA. AMSTRONG, MOD. HEM91, No. SERIE 313134-80-5-02, 87.2 LB/HR"
},
"1.95":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "H-13, MCA. AMSTRONG, MOD. HEM91, No. SERIE 313134-80-3-02, 33.7 LB/HR"
},
"1.96":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "H-14, MCA. AMSTRONG, MOD. HEM91, No. SERIE 313134-80-4-02, 13.4 LB/HR"
},
"1.97":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "H-15, MCA. AMSTRONG, MOD. HEM91, No. SERIE 313134-80-2-02, 57.7 LB/HR"
},
"1.98":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "H-16, MCA. AMSTRONG, MOD. HEM90, No. SERIE 313134-60-1-02, 41.6 LB/HR"
},
"1.99":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "H-17, MCA. AMSTRONG, MOD. HEM90, No. SERIE 313134-60-1-02, 57.7 LB/HR"
},
"1.100":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "H-18, MCA. AMSTRONG, MOD. HEM90, No. SERIE 313134-60-1-02, 41.6 LB/HR"
},
"1.101":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "H-19, MCA. AMSTRONG, MOD. HEM90, No. SERIE 313134-50-4-02, 57.7 LB/HR"
},
"1.102":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "H-20, MCA. AMSTRONG, MOD. HEM90, No. SERIE 314477-10-1-02, 41.6 LB/HR"
},
"1.103":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "H-21, MCA. AMSTRONG, MOD. HEM91, No. SERIE 313134-80-1-02, 6.8 LB/HR"
},
"1.104":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "H-22, MCA. AMSTRONG, MOD. HEM91, No. SERIE 3134-70-1-02, 13.4 LB/HR"
},
"1.105":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "H-23, MCA. AMSTRONG, MOD. HEM91, No. SERIE 313134-80-6-02, 18.4 LB/HR"
},
"1.106":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "H-24, MCA. AMSTRONG, MOD. HEM91, No. SERIE 313134-80-6-02, 55.2 LB/HR"
},
"1.107":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "H-25, MCA. AMSTRONG, MOD. HEM90, No. SERIE 313134-30-2-20, 43.6 LB/HR"
},
"1.108":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "H-26, MCA. AMSTRONG, MOD. HEM92, No. SERIE 313134-100-1-02, 3.6 LB/HR"
},
"1.109":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "H-27, MCA. AMSTRONG, MOD. HEM92, No. SERIE 313134-100-1-02, 9.2 LB/HR"
},
"1.110":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "H-28, MCA. AMSTRONG, MOD. HEM92, No. SERIE 313134-60-1-04, 12.5 LB/HR"
},
"1.111":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "H-29, MCA. AMSTRONG, MOD. HEM92, No. SERIE 313134-100-1-02, 12.5 LB/HR"
},
"1.112":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "UC-1, MCA. MC QUAY, MOD. PCK060-3, No. SERIE 201439291 CON MOTOR DE 1/3 H.P."
},
"1.113":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "UC-2, MCA. MC QUAY, MOD. PCK048-3, No. SERIE 112424581 CON MOTOR DE 1/2 H.P."
},
"1.114":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "UC-3, MCA. MC QUAY, MOD. CE-120-4A, No. SERIE 7424303 CON MOTOR DE 2,6 H.P."
},
"1.115":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "UC-4, MCA. MC QUAY, MOD. CE-120-4A, No. SERIE 10431815 CON MOTOR DE 1/3 H.P."
},
"1.116":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "UC-5, MCA. MC QUAY, MOD. CE-120-4A, No. SERIE 7424306 CON MOTOR DE 2,6 H.P."
},
"1.117":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "UC-6, MCA. MC QUAY, MOD. CE-120-4A, No. SERIE 7424286 CON MOTOR DE 2,6 H.P."
},
"1.118":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "UC-7, MCA. MC QUAY, MOD. CE-120-4A, No. SERIE 10431815 CON MOTOR DE 1/3 H.P."
},
"1.119":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "UC-8, MCA. MC QUAY, MOD. CE-120-4A, No. SERIE 7424306 CON MOTOR DE 2,6 H.P."
},
"1.120":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "UC-9, MCA. MC QUAY, MOD. CE-120-4A, No. SERIE 7424286 CON MOTOR DE 2,6 H.P."
},
"1.121":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "UC-10, MCA. MC QUAY, MOD. HDP181A, No. SERIE 102509726 CON MOTOR DE 1/15 H.P."
},
"1.122":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "UNIDAD TIPO PAQUETE, MCA. YORK, MOD. CKL120-4, No. SERIE 208449837CON MOTOR DE 10 H.P."
},
"1.123":{
 "unidad": "CENTRO MÉDICO ISSEMYM TOLUCA LIC. ARTURO MONTIEL ROJAS", 
 "equipo": "UNIDADES GENERADORAS DE AGUA HELADA (CHILLERS) MOD. WSC048J"
}
}
}
}
